# CMake generated Testfile for 
# Source directory: /home/master01/CC_Exp/src/network/examples
# Build directory: /home/master01/CC_Exp/cmake-cache/src/network/examples
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-bit-serializer "ns3.39-bit-serializer-debug")
set_tests_properties(ctest-bit-serializer PROPERTIES  WORKING_DIRECTORY "/home/master01/CC_Exp/build/src/network/examples/" _BACKTRACE_TRIPLES "/home/master01/CC_Exp/build-support/macros-and-definitions.cmake;1584;add_test;/home/master01/CC_Exp/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/home/master01/CC_Exp/build-support/custom-modules/ns3-module-macros.cmake;439;build_exec;/home/master01/CC_Exp/src/network/examples/CMakeLists.txt;13;build_lib_example;/home/master01/CC_Exp/src/network/examples/CMakeLists.txt;0;")
add_test(ctest-main-packet-header "ns3.39-main-packet-header-debug")
set_tests_properties(ctest-main-packet-header PROPERTIES  WORKING_DIRECTORY "/home/master01/CC_Exp/build/src/network/examples/" _BACKTRACE_TRIPLES "/home/master01/CC_Exp/build-support/macros-and-definitions.cmake;1584;add_test;/home/master01/CC_Exp/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/home/master01/CC_Exp/build-support/custom-modules/ns3-module-macros.cmake;439;build_exec;/home/master01/CC_Exp/src/network/examples/CMakeLists.txt;13;build_lib_example;/home/master01/CC_Exp/src/network/examples/CMakeLists.txt;0;")
add_test(ctest-main-packet-tag "ns3.39-main-packet-tag-debug")
set_tests_properties(ctest-main-packet-tag PROPERTIES  WORKING_DIRECTORY "/home/master01/CC_Exp/build/src/network/examples/" _BACKTRACE_TRIPLES "/home/master01/CC_Exp/build-support/macros-and-definitions.cmake;1584;add_test;/home/master01/CC_Exp/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/home/master01/CC_Exp/build-support/custom-modules/ns3-module-macros.cmake;439;build_exec;/home/master01/CC_Exp/src/network/examples/CMakeLists.txt;13;build_lib_example;/home/master01/CC_Exp/src/network/examples/CMakeLists.txt;0;")
add_test(ctest-packet-socket-apps "ns3.39-packet-socket-apps-debug")
set_tests_properties(ctest-packet-socket-apps PROPERTIES  WORKING_DIRECTORY "/home/master01/CC_Exp/build/src/network/examples/" _BACKTRACE_TRIPLES "/home/master01/CC_Exp/build-support/macros-and-definitions.cmake;1584;add_test;/home/master01/CC_Exp/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/home/master01/CC_Exp/build-support/custom-modules/ns3-module-macros.cmake;439;build_exec;/home/master01/CC_Exp/src/network/examples/CMakeLists.txt;13;build_lib_example;/home/master01/CC_Exp/src/network/examples/CMakeLists.txt;0;")
add_test(ctest-lollipop-comparisons "ns3.39-lollipop-comparisons-debug")
set_tests_properties(ctest-lollipop-comparisons PROPERTIES  WORKING_DIRECTORY "/home/master01/CC_Exp/build/src/network/examples/" _BACKTRACE_TRIPLES "/home/master01/CC_Exp/build-support/macros-and-definitions.cmake;1584;add_test;/home/master01/CC_Exp/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/home/master01/CC_Exp/build-support/custom-modules/ns3-module-macros.cmake;439;build_exec;/home/master01/CC_Exp/src/network/examples/CMakeLists.txt;13;build_lib_example;/home/master01/CC_Exp/src/network/examples/CMakeLists.txt;0;")
