# CMake generated Testfile for 
# Source directory: /home/master01/CC_Exp/src/mobility/examples
# Build directory: /home/master01/CC_Exp/cmake-cache/src/mobility/examples
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-bonnmotion-ns2-example "ns3.39-bonnmotion-ns2-example-debug")
set_tests_properties(ctest-bonnmotion-ns2-example PROPERTIES  WORKING_DIRECTORY "/home/master01/CC_Exp/build/src/mobility/examples/" _BACKTRACE_TRIPLES "/home/master01/CC_Exp/build-support/macros-and-definitions.cmake;1584;add_test;/home/master01/CC_Exp/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/home/master01/CC_Exp/build-support/custom-modules/ns3-module-macros.cmake;439;build_exec;/home/master01/CC_Exp/src/mobility/examples/CMakeLists.txt;11;build_lib_example;/home/master01/CC_Exp/src/mobility/examples/CMakeLists.txt;0;")
add_test(ctest-main-random-topology "ns3.39-main-random-topology-debug")
set_tests_properties(ctest-main-random-topology PROPERTIES  WORKING_DIRECTORY "/home/master01/CC_Exp/build/src/mobility/examples/" _BACKTRACE_TRIPLES "/home/master01/CC_Exp/build-support/macros-and-definitions.cmake;1584;add_test;/home/master01/CC_Exp/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/home/master01/CC_Exp/build-support/custom-modules/ns3-module-macros.cmake;439;build_exec;/home/master01/CC_Exp/src/mobility/examples/CMakeLists.txt;11;build_lib_example;/home/master01/CC_Exp/src/mobility/examples/CMakeLists.txt;0;")
add_test(ctest-main-random-walk "ns3.39-main-random-walk-debug")
set_tests_properties(ctest-main-random-walk PROPERTIES  WORKING_DIRECTORY "/home/master01/CC_Exp/build/src/mobility/examples/" _BACKTRACE_TRIPLES "/home/master01/CC_Exp/build-support/macros-and-definitions.cmake;1584;add_test;/home/master01/CC_Exp/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/home/master01/CC_Exp/build-support/custom-modules/ns3-module-macros.cmake;439;build_exec;/home/master01/CC_Exp/src/mobility/examples/CMakeLists.txt;11;build_lib_example;/home/master01/CC_Exp/src/mobility/examples/CMakeLists.txt;0;")
add_test(ctest-ns2-mobility-trace "ns3.39-ns2-mobility-trace-debug")
set_tests_properties(ctest-ns2-mobility-trace PROPERTIES  WORKING_DIRECTORY "/home/master01/CC_Exp/build/src/mobility/examples/" _BACKTRACE_TRIPLES "/home/master01/CC_Exp/build-support/macros-and-definitions.cmake;1584;add_test;/home/master01/CC_Exp/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/home/master01/CC_Exp/build-support/custom-modules/ns3-module-macros.cmake;439;build_exec;/home/master01/CC_Exp/src/mobility/examples/CMakeLists.txt;11;build_lib_example;/home/master01/CC_Exp/src/mobility/examples/CMakeLists.txt;0;")
add_test(ctest-main-grid-topology "ns3.39-main-grid-topology-debug")
set_tests_properties(ctest-main-grid-topology PROPERTIES  WORKING_DIRECTORY "/home/master01/CC_Exp/build/src/mobility/examples/" _BACKTRACE_TRIPLES "/home/master01/CC_Exp/build-support/macros-and-definitions.cmake;1584;add_test;/home/master01/CC_Exp/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/home/master01/CC_Exp/build-support/custom-modules/ns3-module-macros.cmake;439;build_exec;/home/master01/CC_Exp/src/mobility/examples/CMakeLists.txt;19;build_lib_example;/home/master01/CC_Exp/src/mobility/examples/CMakeLists.txt;0;")
add_test(ctest-mobility-trace-example "ns3.39-mobility-trace-example-debug")
set_tests_properties(ctest-mobility-trace-example PROPERTIES  WORKING_DIRECTORY "/home/master01/CC_Exp/build/src/mobility/examples/" _BACKTRACE_TRIPLES "/home/master01/CC_Exp/build-support/macros-and-definitions.cmake;1584;add_test;/home/master01/CC_Exp/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/home/master01/CC_Exp/build-support/custom-modules/ns3-module-macros.cmake;439;build_exec;/home/master01/CC_Exp/src/mobility/examples/CMakeLists.txt;28;build_lib_example;/home/master01/CC_Exp/src/mobility/examples/CMakeLists.txt;0;")
add_test(ctest-reference-point-group-mobility-example "ns3.39-reference-point-group-mobility-example-debug")
set_tests_properties(ctest-reference-point-group-mobility-example PROPERTIES  WORKING_DIRECTORY "/home/master01/CC_Exp/build/src/mobility/examples/" _BACKTRACE_TRIPLES "/home/master01/CC_Exp/build-support/macros-and-definitions.cmake;1584;add_test;/home/master01/CC_Exp/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/home/master01/CC_Exp/build-support/custom-modules/ns3-module-macros.cmake;439;build_exec;/home/master01/CC_Exp/src/mobility/examples/CMakeLists.txt;37;build_lib_example;/home/master01/CC_Exp/src/mobility/examples/CMakeLists.txt;0;")
