#!/usr/bin/env bash
# LPCC switch-buffer / flow-table-memory sweep vs concurrent flow count.
# Reproducible: fixed seed flow files, pinned RngRun, ENABLE_TRACE off, monitor node 74.
# Buffer table uses max-over-all-switches (default). Appends the table below the
# existing content of overhead.md.
set -e
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/config.sh"

COUNTS="${COUNTS:-64,256,1024,4096,16384}"
CONFIG_TEMPLATE="$NS3/examples/PowerTCP/config-burst.txt"
OUT_ROOT="$NS3/examples/PowerTCP/dump_burst_overhead"
FLOW_DIR="$NS3/examples/PowerTCP/sweep_flows"
BIN="${BIN:-$NS3/build/examples/PowerTCP/ns3.39-powertcp-evaluation-burst-optimized}"
OUT_MD="$NS3/examples/PowerTCP/overhead.md"
PER_RUN_TIMEOUT="${PER_RUN_TIMEOUT:-10800}"

[ -x "$BIN" ] || { echo "[*] building binary"; (cd "$NS3" && CXXFLAGS=-w ./ns3 build examples/PowerTCP/powertcp-evaluation-burst); }

mkdir -p "$OUT_ROOT" "$FLOW_DIR"
python3 "$SCRIPT_DIR/gen-sweep-flows.py" --out_dir "$FLOW_DIR" --sizes "$COUNTS" --bytes 1000000 \
    --start_time 0.12 --rand_start_window 0.01

cd "$NS3"
IFS=',' read -ra NLIST <<< "$COUNTS"
for N in "${NLIST[@]}"; do
    SIM_STOP=0.35
    (( N > 4096 )) && echo "[warn] N=$N is heavy (long wall-clock; peaks still captured early)"
    run_dir="$OUT_ROOT/lpcc/$N"; mkdir -p "$run_dir"; run_conf="$run_dir/config.txt"
    awk -v flow="$FLOW_DIR/flow-burstExp-$N.txt" -v fct="$run_dir/fct.txt" \
        -v pfc="$run_dir/pfc.txt" -v ftmon="$run_dir/flow_table.txt" \
        -v qlen="$run_dir/qlen.txt" -v stop="$SIM_STOP" '
        $1=="FLOW_FILE"{print "FLOW_FILE "flow;next}
        $1=="FCT_OUTPUT_FILE"{print "FCT_OUTPUT_FILE "fct;next}
        $1=="PFC_OUTPUT_FILE"{print "PFC_OUTPUT_FILE "pfc;next}
        $1=="FLOW_TABLE_MON_FILE"{print "FLOW_TABLE_MON_FILE "ftmon;next}
        $1=="QLEN_MON_FILE"{print "QLEN_MON_FILE "qlen;next}
        $1=="SIMULATOR_STOP_TIME"{print "SIMULATOR_STOP_TIME "stop;next}
        $1=="ENABLE_TRACE"{print "ENABLE_TRACE 0";next}
        {print}' "$CONFIG_TEMPLATE" > "$run_conf"
    grep -q "^FLOW_TABLE_MON_FILE " "$run_conf" || { echo "FLOW_TABLE_MON_FILE $run_dir/flow_table.txt" >> "$run_conf"; echo "FLOW_TABLE_MON_INTERVAL_NS 100000" >> "$run_conf"; }

    echo "[*] LPCC N=$N SIM_STOP=$SIM_STOP -> $run_dir"
    timeout "$PER_RUN_TIMEOUT" "$BIN" --conf="$run_conf" --algorithm=9 --transportMode=0 \
        --flowControlMode=0 --wien=false --delayWien=false --windowCheck=0 \
        --monitorSwitchId=74 --monitorThroughputBps=100000000000 --RngRun=1 \
        > /dev/null 2> "$run_dir/run.err" || echo "    (run timed out or failed)"
    echo "    ft lines=$(wc -l < "$run_dir/flow_table.txt" 2>/dev/null || echo 0)"
done

# Provenance stamp + append the buffer table to overhead.md
COMMIT=$(git -C "$NS3" rev-parse --short HEAD 2>/dev/null || echo unknown)
CONF_SHA=$(sha256sum "$CONFIG_TEMPLATE" | cut -c1-12)
{ echo ""; echo "<!-- generated by run-overhead-buffer.sh | commit=$COMMIT | counts=$COUNTS | config_sha=$CONF_SHA | flows=uniform bytes=1000000 RngRun=1 -->"; } >> "$OUT_MD"
python3 "$SCRIPT_DIR/analyze-overhead.py" --table buffer --alg lpcc --root "$OUT_ROOT" \
    --counts "$COUNTS" --buffer-mb 128 --out "$OUT_MD" --append
echo "## OVERHEAD-BUFFER SWEEP FINISHED -> $OUT_MD ##"
