#!/usr/bin/env bash
# A/B test: isolate flow-table maintenance overhead on the forwarding path.
# Run DCQCN (does NOT read the flow table) twice per N:
#   on:  FLOW_TABLE_MAINTENANCE 1  -> Insert/Clean still execute (pure overhead)
#   off: FLOW_TABLE_MAINTENANCE 0  -> Insert/Clean compiled out at runtime
# Same workload, same CC, same SIM_STOP. Diff = forwarding cost of maintenance.
set -e
set -o pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/config.sh"

CONFIG_TEMPLATE="$NS3/examples/PowerTCP/config-burst.txt"
OUT_ROOT="$NS3/examples/PowerTCP/dump_burst_overhead_ab"
FLOW_DIR="$NS3/examples/PowerTCP/sweep_flows_ab"
BIN="${BIN:-$NS3/build/examples/PowerTCP/ns3.39-powertcp-evaluation-burst-optimized}"
[ -x "$BIN" ] || (cd "$NS3" && CXXFLAGS=-w ./ns3 build examples/PowerTCP/powertcp-evaluation-burst)
PER_RUN_TIMEOUT="${PER_RUN_TIMEOUT:-3600}"

COUNTS="${COUNTS:-64,256,1024,4096,16384}"
TABLE_COUNTS="${TABLE_COUNTS:-64,256,1024,4096,16384}"
IFS=',' read -ra NLIST <<< "$COUNTS"

cd "$NS3"

python3 "$SCRIPT_DIR/gen-sweep-flows.py" --out_dir "$FLOW_DIR" --sizes "$COUNTS" --bytes 64000 \
    --start_time 0.12 --rand_start_window 0.01

alg=dcqcn; cc=1; fc=0; tp=0; window=0; wien=false; delay=false

for N in "${NLIST[@]}"; do
    if (( N >= 16384 )); then SIM_STOP=0.6; else SIM_STOP=0.35; fi
    for maint in on off; do
        run_dir="$OUT_ROOT/${maint}/$N"
        mkdir -p "$run_dir"
        run_conf="$run_dir/config.txt"
        if [[ "$maint" == "on" ]]; then maint_val=1; else maint_val=0; fi
        awk -v flow="$FLOW_DIR/flow-burstExp-$N.txt" \
            -v fct="$run_dir/fct.txt" \
            -v pfc="$run_dir/pfc.txt" \
            -v ftmon="$run_dir/flow_table.txt" \
            -v qlen="$run_dir/qlen.txt" \
            -v stop="$SIM_STOP" \
            -v maint_val="$maint_val" '
            $1 == "FLOW_FILE"           { print "FLOW_FILE " flow; next }
            $1 == "FCT_OUTPUT_FILE"     { print "FCT_OUTPUT_FILE " fct; next }
            $1 == "PFC_OUTPUT_FILE"     { print "PFC_OUTPUT_FILE " pfc; next }
            $1 == "FLOW_TABLE_MON_FILE" { print "FLOW_TABLE_MON_FILE " ftmon; next }
            $1 == "QLEN_MON_FILE"       { print "QLEN_MON_FILE " qlen; next }
            $1 == "SIMULATOR_STOP_TIME" { print "SIMULATOR_STOP_TIME " stop; next }
            $1 == "FLOW_TABLE_MAINTENANCE" { print "FLOW_TABLE_MAINTENANCE " maint_val; next }
            $1 == "ENABLE_TRACE"        { print "ENABLE_TRACE 0"; next }
            { print }
        ' "$CONFIG_TEMPLATE" > "$run_conf"
        # Append maintenance flag if missing in template.
        grep -q "^FLOW_TABLE_MAINTENANCE " "$run_conf" || echo "FLOW_TABLE_MAINTENANCE $maint_val" >> "$run_conf"
        if [[ "$maint" == "on" ]]; then dmin=20; dmax=50; else dmin=0; dmax=0; fi
        echo "FLOW_TABLE_OP_DELAY_MIN_NS $dmin" >> "$run_conf"
        echo "FLOW_TABLE_OP_DELAY_MAX_NS $dmax" >> "$run_conf"

        echo "[*] alg=$alg N=$N maint=$maint SIM_STOP=$SIM_STOP -> $run_dir"
        START=$(date +%s)
        timeout "$PER_RUN_TIMEOUT" "$BIN" \
            --conf="$run_conf" --algorithm="$cc" --transportMode="$tp" \
            --flowControlMode="$fc" --wien="$wien" --delayWien="$delay" \
            --windowCheck="$window" \
            --monitorSwitchId=74 --monitorThroughputBps=100000000000 --RngRun=1 2>&1 \
            | grep -E --line-buffered 'MONITOR_TARGET|PortAgg -1 throughput' > "$run_dir/run.log" \
            || echo "    (run failed/timeout or no monitor lines)"
        END=$(date +%s)
        echo "    elapsed=$((END - START))s, fct=$(wc -l < "$run_dir/fct.txt" 2>/dev/null), ft=$(wc -l < "$run_dir/flow_table.txt" 2>/dev/null)"
    done
done
# Provenance stamp, then append the regenerated table below it.
OUT_MAINT="$NS3/examples/PowerTCP/overhead-maint.md"
COMMIT=$(git -C "$NS3" rev-parse --short HEAD 2>/dev/null || echo unknown)
CONF_SHA=$(sha256sum "$CONFIG_TEMPLATE" | cut -c1-12)
printf '<!-- generated by script-ab-maintenance.sh | commit=%s | counts=%s | config_sha=%s | flows=uniform bytes=64000 start[0.12,0.13] SIM=0.35(64-4096)/0.6(16384) RngRun=1 | on-arm FLOW_TABLE_OP_DELAY 20-50ns -->\n' \
    "$COMMIT" "$TABLE_COUNTS" "$CONF_SHA" > "$OUT_MAINT"
python3 "$SCRIPT_DIR/analyze-overhead.py" --table maintenance \
    --root "$OUT_ROOT" --counts "$TABLE_COUNTS" \
    --out "$OUT_MAINT" --append
echo "## wrote $OUT_MAINT ##"
echo "## A/B MAINTENANCE TEST FINISHED ##"
