# CMake generated Testfile for 
# Source directory: /home/master01/CC_Exp/src/nix-vector-routing/examples
# Build directory: /home/master01/CC_Exp/cmake-cache/src/nix-vector-routing/examples
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-nix-simple "ns3.39-nix-simple-debug")
set_tests_properties(ctest-nix-simple PROPERTIES  WORKING_DIRECTORY "/home/master01/CC_Exp/build/src/nix-vector-routing/examples/" _BACKTRACE_TRIPLES "/home/master01/CC_Exp/build-support/macros-and-definitions.cmake;1584;add_test;/home/master01/CC_Exp/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/home/master01/CC_Exp/build-support/custom-modules/ns3-module-macros.cmake;439;build_exec;/home/master01/CC_Exp/src/nix-vector-routing/examples/CMakeLists.txt;11;build_lib_example;/home/master01/CC_Exp/src/nix-vector-routing/examples/CMakeLists.txt;0;")
add_test(ctest-nix-simple-multi-address "ns3.39-nix-simple-multi-address-debug")
set_tests_properties(ctest-nix-simple-multi-address PROPERTIES  WORKING_DIRECTORY "/home/master01/CC_Exp/build/src/nix-vector-routing/examples/" _BACKTRACE_TRIPLES "/home/master01/CC_Exp/build-support/macros-and-definitions.cmake;1584;add_test;/home/master01/CC_Exp/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/home/master01/CC_Exp/build-support/custom-modules/ns3-module-macros.cmake;439;build_exec;/home/master01/CC_Exp/src/nix-vector-routing/examples/CMakeLists.txt;11;build_lib_example;/home/master01/CC_Exp/src/nix-vector-routing/examples/CMakeLists.txt;0;")
add_test(ctest-nms-p2p-nix "ns3.39-nms-p2p-nix-debug")
set_tests_properties(ctest-nms-p2p-nix PROPERTIES  WORKING_DIRECTORY "/home/master01/CC_Exp/build/src/nix-vector-routing/examples/" _BACKTRACE_TRIPLES "/home/master01/CC_Exp/build-support/macros-and-definitions.cmake;1584;add_test;/home/master01/CC_Exp/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/home/master01/CC_Exp/build-support/custom-modules/ns3-module-macros.cmake;439;build_exec;/home/master01/CC_Exp/src/nix-vector-routing/examples/CMakeLists.txt;11;build_lib_example;/home/master01/CC_Exp/src/nix-vector-routing/examples/CMakeLists.txt;0;")
add_test(ctest-nix-double-wifi "ns3.39-nix-double-wifi-debug")
set_tests_properties(ctest-nix-double-wifi PROPERTIES  WORKING_DIRECTORY "/home/master01/CC_Exp/build/src/nix-vector-routing/examples/" _BACKTRACE_TRIPLES "/home/master01/CC_Exp/build-support/macros-and-definitions.cmake;1584;add_test;/home/master01/CC_Exp/build-support/macros-and-definitions.cmake;1659;set_runtime_outputdirectory;/home/master01/CC_Exp/build-support/custom-modules/ns3-module-macros.cmake;439;build_exec;/home/master01/CC_Exp/src/nix-vector-routing/examples/CMakeLists.txt;22;build_lib_example;/home/master01/CC_Exp/src/nix-vector-routing/examples/CMakeLists.txt;0;")
